language: python
sudo: true
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - 2.7
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads -c travis.cfg annotate
  - bin/buildout -N buildout:download-cache=downloads -c travis.cfg
services:
  - xvfb
before_script:
- export DISPLAY=:99.0
- firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls
notifications:
  email:
    - devs@imio.be
