language: python
sudo: true
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
install:
  - python bootstrap-buildout.py
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads
services:
  - xvfb
before_script:
- export DISPLAY=:99.0
- firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls
notifications:
  email:
    - devs@imio.be
